#!/bin/sh

export EDITOR=nvim
export VISUAL=nvim
export MANPAGER="nvim +Man!"

# Clean up
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GNUPGHOME="$XDG_CACHE_HOME"/gnupg

# History
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export PYTHON_HISTORY="$XDG_STATE_HOME"/python_history
export CALCHISTFILE="$XDG_CACHE_HOME"/calc_history
export PHP_HISTFILE="$XDG_STATE_HOME"/php/history
export GDBHISTFILE="$XDG_DATA_HOME"/gdb/history

# Resource files
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

# Xorg
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
